- hosts: all
  roles:
    - lorem
  become: true
  gather_facts: no
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-southeast-1
    ansible_aws_ssm_access_key_id: "{{ access_key_id }}"
    ansible_aws_ssm_secret_access_key: "{{ aws_secret_access_key }}"
    ansible_aws_ssm_bucket_name: test-ansible-ec2-ssm
